travis:
  secure:
    BINSTAR_TOKEN: yoXh1NqJtaiPBCxUNeklTcWCCxuqRecC3t0lGmWxxWvUMXQZJfPuK1NmUQpytgjlOXnRNB8aIhXAmixPXA/llezlIQOqgP10J86/f54njRh9y2OUgIQUo3yCr2/VANF9Jd9rbnciOxnC3YamSI2wU54v4ulJgMDb0XyhpILx6ni8PCvcOdLbxVcVPaYY7LAXhnt2Q2tDhR3AOgtUkY5wENTeJ8DaWR98FeqZv2ArpCw+ef9ad30REi2GwbYiCWJCOmaEO4CvdlsG+7Nz6D2KmR6peObYyrVKwAPe+6W+NGNgVN69451fBTH1kDd9j9kcB5KdnLDB66fuwCZytAET/5xTzId6G35zm/j4KfJ3gvW1/izot2Xll81kpAOch4lSgSdkoJYYGS5b1LjCw2M/ILkpIxVK8UlYy2KdHwDu+QjuaRfA4fbs/X0s0/kUuFb20hIiLPt3EBdHkk/b0VHsjJAz3VSRpGrYy/pO8ZYl/0h7Jc71w7vLOtot4D6uXAPdUYFrims0OsJL/ePm+7eKKqmomho1zIYfT4/PxnXoZ/Y5Gd3ikjyJbJyF6xNd4ykFOkqEoq4YYo+JhGuPjXpkj/3Oc8PU5HPphNTNoqNXHq8YTuivVRL/PX+zHPFbN0MUateaF8q5hAp/G/X4AUHiSNFNkkMxUJLU9Q+qv7tWriI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
